# Path to the folder with the simc executable
SimcPath: D:\Dev\SimulationCraft

# How many threads to use, put a number or a formula using "max" for all cores
Threads: max - 1

# What file type to write reports to (available: json, csv; you can specify multiple with | as seperator)
OutputExt: csv

# Abort the simulation if the end-of-sim log file already exists.
AbortOnExistingReport: false

# Wether or not the simc text logs should be saved
SaveSimcTextLogs: true

###
### You can most likely leave the following the way they are.
###

# Where tool-wide config files are stored
ConfigFolder: conf

# Where reports / CSV files will be saved
ReportsFolder: reports

# Where simc log files will be saved
LogsFolder: logs

# Where generated simc files will be saved
GeneratedFolder: generated

# Where templates for the scripts are placed
ProfilesFolder: profiles
# Additional template sources in the SimC source
SimcProfileFolders:
- profiles/PreRaids/
- profiles/Tier22/

# Where archiver puts packed reports, logs and input
ArchivesFolder: archives

###
### Run.rb
###

# Orders (scripts, fightstyles) to run
RunOrders: [
  [["RaceSimulation", "TrinketSimulation", "AzeriteSimulation", "Combinator"], ["1T"]],
  [["RaceSimulation", "TrinketSimulation", "AzeriteSimulation", "Combinator"], ["2T"]],
  [["RaceSimulation", "TrinketSimulation", "AzeriteSimulation", "Combinator"], ["1TA"]],
  [["RaceSimulation", "TrinketSimulation", "AzeriteSimulation", "Combinator"], ["Dungeon"]]
]

# Amounts of same Azerite trait stacks to sim. (Combinator-0A, Combinator-1A, ...)
RunCombinatorAzeriteStacks: [0, 1, 2, 3]

# Classes to run
RunClasses: ["Death-Knight", "Demon-Hunter", "Druid", "Hunter", "Mage", "Monk", "Paladin", "Priest", "Rogue", "Shaman", "Warlock", "Warrior"]

###
### Hero Websites (json output only)
###

# If specified to true, will prepare the report to be used on HeroTC websites like Hero Damage
HeroOutput: false

HeroDamagePath: D:\Dev\HeroDamage
