# Path to the folder with the simc executable
SimcPath: D:\Dev\SimulationCraft

# How many threads to use
Threads: 3

# What file type to write reports to (available: json, csv; you can specify multiple with | as seperator)
OutputExt: csv

###
### You can most likely leave the following the way they are.
###

# Where tool-wide config files are stored
ConfigFolder: conf

# Where reports / CSV files will be saved
ReportsFolder: reports

# Where simc log files will be saved
LogsFolder: logs

# Where generated simc files will be saved
GeneratedFolder: generated

# Where templates for the scripts are placed
ProfilesFolder: profiles

# Where archiver puts packed reports, logs and input
ArchivesFolder: archives

###
### Run.rb
###

# Orders (scripts, fightstyles) to run
RunOrders: [
  [["RaceSimulation", "TrinketSimulation", "Combinator"], ["1T"]],
  [["RaceSimulation", "TrinketSimulation"], ["2T", "3T", "1TA"]],
  [["Combinator"], ["2T", "3T", "1TA"]],
]

# Classes to run
RunClasses: ["DeathKnight", "DemonHunter", "Druid", "Hunter", "Mage", "Monk", "Paladin", "Priest", "Rogue", "Shaman", "Warlock", "Warrior"]

###
### Hero Websites (json output only)
###

# If specified to true, will prepare the report to be used on HeroTC websites like Hero Damage
HeroOutput: false
